# AirCoin stellar.toml

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

DOMAIN="https://qaircoin.io"

ACCOUNTS=[
"GC6OYQJIZF3HFXCYPFCBXYXNGIBQ4TNSFUBUXQJOZWIP6F3YZK4QH3VQ",
"GCTBATCNXTDRHDRBJ2PZREPN5GNCI5GVZUNF6CQ22LZVF2TIFXQ5V4XF"]

[DOCUMENTATION]
ORG_NAME="Aircoin"
ORG_URL="https://www.qaircoin.io"
ORG_LOGO="https://qaircoin.io/wp-content/uploads/2022/04/air128c.png"
ORG_DESCRIPTION="Scopuly - Stellar Wallet & SDEX. A simple and secure cross-platform Stellar wallet that gives you the most complete control over your Stellar account. In Scopuly, you can: securely store and transfer crypto assets; make cross-border multicurrency payments; buy / sell crypto for fiat; issue your own tokens and trade on the SDEX decentralized exchange in real time with no fees. Scopuly is the perfect way to decentralize, store, manage, invest, trade, pay and move crypto assets."
ORG_TWITTER="https://twitter.com/aircoin"
ORG_GITHUB="https://github.com/aircoin"
ORG_TELEGRAM="https://t.me/aircoin"
ORG_OFFICIAL_EMAIL="info@aircoin.com"

[[CURRENCIES]]
code="AirCoin"
name="Air Coin"
issuer="GD6EU27ESEEWK7H2TFLFJTQOMMNLMVZIQPRSLWUXKXYPGQFHO5KLSUFE"
desc="QAirCoin allows tourists across multiple countries to exercise their share of influence within their favourite place/club/natural reserve."
image="https://qaircoin.io/wp-content/uploads/2022/04/air128c.png"
status="live"
display_decimals=7
fixed_number=4170000000


[[PRINCIPALS]]
email="info@aircoin.com"
twitter="@aircoin"
telegram="@aircoin"